# Generated by Django 4.2 on 2023-04-28 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dia de criação', models.DateField(auto_now_add=True)),
                ('Dia da modificação', models.DateField(auto_now=True)),
                ('Nome do projeto', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pessoas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dia de criação', models.DateField(auto_now_add=True)),
                ('Dia da modificação', models.DateField(auto_now=True)),
                ('Nome', models.CharField(max_length=100)),
                ('Sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('Cargo', models.CharField(choices=[('PD', 'Professor Doutor'), ('PA', 'Professor Adjunto')], max_length=100)),
                ('projeto', models.ManyToManyField(to='core.projeto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dia de criação', models.DateField(auto_now_add=True)),
                ('Dia da modificação', models.DateField(auto_now=True)),
                ('Nome da empresa', models.CharField(max_length=100)),
                ('projeto', models.ManyToManyField(to='core.projeto')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
