# Generated by Django 4.2 on 2023-05-24 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Creates date', models.DateField(auto_now_add=True)),
                ('Modify date', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('Sex', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('Post', models.CharField(choices=[('Professor Doutor', 'Professor Doutor'), ('Professor Adjunto', 'Professor Adjunto'), ('Pesquisador', 'Pesquisador'), ('Pós-Doc', 'Pós-Doc'), ('Doutorando', 'Doutorando'), ('Mestrando', 'Mestrando'), ('Iniciação científica', 'Iniciação científica')], max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Creates date', models.DateField(auto_now_add=True)),
                ('Modify date', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('Over date', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reasearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Creates date', models.DateField(auto_now_add=True)),
                ('Modify date', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('idperson', models.ManyToManyField(to='core.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Creates date', models.DateField(auto_now_add=True)),
                ('Modify date', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('idreasearch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.reasearch')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='person',
            name='projeto',
            field=models.ManyToManyField(to='core.project'),
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Creates date', models.DateField(auto_now_add=True)),
                ('Modify date', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('idreasearch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.reasearch')),
                ('videos', models.ManyToManyField(to='core.videos')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Creates date', models.DateField(auto_now_add=True)),
                ('Modify date', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('idmetadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.metadata')),
                ('idreasearch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.reasearch')),
                ('videos', models.ManyToManyField(to='core.videos')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Creates date', models.DateField(auto_now_add=True)),
                ('Modify date', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('project', models.ManyToManyField(to='core.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Creates date', models.DateField(auto_now_add=True)),
                ('Modify date', models.DateField(auto_now=True)),
                ('type', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=30)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Creates date', models.DateField(auto_now_add=True)),
                ('Modify date', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('link_path', models.CharField(max_length=100)),
                ('files', models.ManyToManyField(to='core.files')),
                ('idreasearch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.reasearch')),
                ('metadata', models.ManyToManyField(to='core.metadata')),
                ('person', models.ManyToManyField(to='core.person')),
                ('videos', models.ManyToManyField(to='core.videos')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
