# Generated by Django 4.2 on 2023-04-28 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoas',
            name='Cargo',
            field=models.CharField(choices=[('Professor Doutor', 'Professor Doutor'), ('Professor Adjunto', 'Professor Adjunto'), ('Pesquisador', 'Pesquisador'), ('Pós-Doc', 'Pós-Doc'), ('Doutorando', 'Doutorando'), ('Mestrando', 'Mestrando')], max_length=100),
        ),
    ]
