# Generated by Django 4.2 on 2023-05-24 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reasearch',
            old_name='idperson',
            new_name='person',
        ),
        migrations.AddField(
            model_name='reasearch',
            name='project',
            field=models.ManyToManyField(to='core.project'),
        ),
    ]
