# Generated by Django 4.2 on 2023-05-24 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_project_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enterprise',
            options={'verbose_name': 'Enterprise', 'verbose_name_plural': 'Enterprises'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
    ]
