# Generated by Django 4.2 on 2023-06-14 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_post_people_post_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='post',
            new_name='position',
        ),
    ]
