# Generated by Django 4.2 on 2023-04-28 21:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_empresas_nome_da_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='Data de término',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
