# Generated by Django 4.2 on 2023-05-24 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_enterprise_options_alter_project_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enterprise',
            new_name='SponsorCompany',
        ),
        migrations.AlterModelOptions(
            name='email',
            options={'verbose_name': 'Email', 'verbose_name_plural': 'Email'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Person', 'verbose_name_plural': 'Person'},
        ),
        migrations.AlterModelOptions(
            name='sponsorcompany',
            options={'verbose_name': 'SponsorCompany', 'verbose_name_plural': 'SponsorCompany'},
        ),
        migrations.CreateModel(
            name='ReasearchLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Creates date', models.DateField(auto_now_add=True)),
                ('Modify date', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('Phase', models.CharField(choices=[('Single-phase-flow', 'Single-phase-flow'), ('Two-phase-flow', 'Two-phase-flow'), ('Three-phase-flow', 'Three-phase-flow')], max_length=30)),
                ('person', models.ManyToManyField(to='core.person')),
                ('project', models.ManyToManyField(to='core.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='articles',
            name='idreasearch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.reasearchline'),
        ),
        migrations.AlterField(
            model_name='files',
            name='idreasearch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.reasearchline'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='idreasearch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.reasearchline'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='idreasearch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.reasearchline'),
        ),
        migrations.DeleteModel(
            name='Reasearch',
        ),
    ]
