# Generated by Django 4.2 on 2023-04-28 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_projeto_data_de_término'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='Data de término',
            field=models.DateField(null=True),
        ),
    ]
