# Generated by Django 4.2 on 2023-05-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_person_people_alter_people_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reasearchline',
            options={'verbose_name': 'ReasearchLine', 'verbose_name_plural': 'ReasearchLine'},
        ),
        migrations.AlterField(
            model_name='reasearchline',
            name='Phase',
            field=models.CharField(blank=True, choices=[('Single-phase-flow', 'Single-phase-flow'), ('Two-phase-flow', 'Two-phase-flow'), ('Three-phase-flow', 'Three-phase-flow')], max_length=30),
        ),
    ]
