# Generated by Django 4.2 on 2023-05-01 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_projeto_data_de_término'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresas',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='pessoas',
            options={'verbose_name': 'Pessoas'},
        ),
        migrations.AlterModelOptions(
            name='projeto',
            options={'verbose_name': 'Projeto', 'verbose_name_plural': 'Projetos'},
        ),
    ]
