# Generated by Django 4.2 on 2023-05-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_reasearchline_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReasearchLine',
            new_name='ReasearchLines',
        ),
        migrations.AlterModelOptions(
            name='files',
            options={'verbose_name': 'Files', 'verbose_name_plural': 'Files'},
        ),
        migrations.AlterModelOptions(
            name='metadata',
            options={'verbose_name': 'Metadata', 'verbose_name_plural': 'Metadata'},
        ),
        migrations.AlterModelOptions(
            name='reasearchlines',
            options={'verbose_name': 'ReasearchLines', 'verbose_name_plural': 'ReasearchLines'},
        ),
        migrations.AlterModelOptions(
            name='videos',
            options={'verbose_name': 'Videos', 'verbose_name_plural': 'Videos'},
        ),
        migrations.RenameField(
            model_name='files',
            old_name='idmetadata',
            new_name='metadata',
        ),
        migrations.RenameField(
            model_name='files',
            old_name='idreasearch',
            new_name='reasearchline',
        ),
        migrations.RenameField(
            model_name='videos',
            old_name='idreasearch',
            new_name='reasearchline',
        ),
        migrations.RemoveField(
            model_name='files',
            name='videos',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='idreasearch',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='videos',
        ),
        migrations.AddField(
            model_name='files',
            name='person',
            field=models.ManyToManyField(to='core.people'),
        ),
        migrations.AddField(
            model_name='videos',
            name='file',
            field=models.ManyToManyField(to='core.files'),
        ),
        migrations.AddField(
            model_name='videos',
            name='metadata',
            field=models.ManyToManyField(to='core.metadata'),
        ),
        migrations.DeleteModel(
            name='Articles',
        ),
    ]
