# Generated by Django 4.2 on 2023-05-01 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_empresas_options_alter_pessoas_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoas',
            options={'verbose_name': 'Pessoa', 'verbose_name_plural': 'Pessoas'},
        ),
    ]
