# Generated by Django 4.2 on 2023-05-24 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_reasearchline_reasearchlines_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Creates date', models.DateField(auto_now_add=True)),
                ('Modify date', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('link_path', models.CharField(max_length=100)),
                ('files', models.ManyToManyField(to='core.files')),
                ('metadata', models.ManyToManyField(to='core.metadata')),
                ('person', models.ManyToManyField(to='core.people')),
                ('reasearchline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.reasearchlines')),
                ('videos', models.ManyToManyField(to='core.videos')),
            ],
            options={
                'verbose_name': 'Articles',
                'verbose_name_plural': 'Articles',
            },
        ),
    ]
