# Generated by Django 4.2 on 2023-05-01 03:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_pessoas_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='Nome do projeto',
        ),
        migrations.AddField(
            model_name='projeto',
            name='nome',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
