# Generated by Django 4.2 on 2023-05-24 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_articles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reasearchlines',
            old_name='Phase',
            new_name='phase',
        ),
    ]
