# Generated by Django 4.2 on 2023-05-24 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_phase_reasearchlines_phase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='files',
            new_name='file',
        ),
        migrations.AlterField(
            model_name='files',
            name='metadata',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.metadata'),
        ),
    ]
