# Generated by Django 4.2 on 2023-05-01 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_projeto_nome_do_projeto_projeto_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='nome',
        ),
        migrations.AddField(
            model_name='projeto',
            name='Nome do projeto',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
