# Generated by Django 4.2 on 2023-05-24 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_files_articles_file_alter_files_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='type',
            field=models.CharField(choices=[('Pessoal', 'Pessoal'), ('Educacional', 'Educacional')], max_length=15),
        ),
    ]
