# Generated by Django 4.2 on 2023-05-25 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_email_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadata',
            name='name',
        ),
        migrations.AddField(
            model_name='metadata',
            name='contact',
            field=models.ManyToManyField(to='core.email'),
        ),
        migrations.AddField(
            model_name='metadata',
            name='contributor',
            field=models.ManyToManyField(to='core.people'),
        ),
        migrations.AddField(
            model_name='metadata',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='metadata',
            name='keyword',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='metadata',
            name='notes',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='metadata',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='files',
            name='metadata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.metadata'),
        ),
    ]
