# Generated by Django 4.2 on 2023-05-25 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_metadata_name_metadata_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='keyword',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
