# Generated by Django 4.2 on 2023-05-01 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_projeto_nome_do_projeto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projeto',
            old_name='Nome do projeto',
            new_name='nome',
        ),
    ]
