# Generated by Django 4.2 on 2023-05-01 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_nome_do_projeto_projeto_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
