# Generated by Django 4.2 on 2023-05-28 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_metadata_description_alter_metadata_keyword_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='reasearchline',
        ),
        migrations.RemoveField(
            model_name='videos',
            name='reasearchline',
        ),
        migrations.AddField(
            model_name='metadata',
            name='reasearchline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.reasearchlines'),
        ),
        migrations.RemoveField(
            model_name='videos',
            name='metadata',
        ),
        migrations.AddField(
            model_name='videos',
            name='metadata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.metadata'),
        ),
    ]
