# Generated by Django 4.2 on 2023-05-01 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_projeto_nome'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresas',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pessoas',
            options={},
        ),
        migrations.AlterModelOptions(
            name='projeto',
            options={},
        ),
    ]
