# Generated by Django 4.2 on 2023-05-28 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_files_reasearchline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reasearchlines',
            name='point',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
