# Generated by Django 4.2 on 2023-05-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_reasearchlines_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
