# Generated by Django 4.2 on 2023-05-01 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_nome_projeto_nome_do_projeto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projeto',
            options={'verbose_name': 'Projeto', 'verbose_name_plural': 'Projetos'},
        ),
    ]
