# Generated by Django 4.2 on 2023-05-01 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_projeto_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projeto',
            options={'verbose_name': 'Projeto', 'verbose_name_plural': 'Projetos'},
        ),
    ]
