# Generated by Django 4.2 on 2023-05-08 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_empresas_options_alter_pessoas_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresas',
            old_name='Nome da empresa',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='pessoas',
            old_name='Nome',
            new_name='nome',
        ),
    ]
